/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package osproject;

import java.awt.Cursor;

/**
 *
 * @author Sara
 */
public class intro extends javax.swing.JFrame {

    /**
     * Creates new form intro
     */
    public intro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head1 = new javax.swing.JPanel();
        headlbl1 = new javax.swing.JLabel();
        head2 = new javax.swing.JPanel();
        headlbl2 = new javax.swing.JLabel();
        sjfDes = new javax.swing.JPanel();
        sjfdesLbl = new javax.swing.JLabel();
        sjf = new javax.swing.JPanel();
        sjfLbl = new javax.swing.JLabel();
        rr = new javax.swing.JPanel();
        rrLbl = new javax.swing.JLabel();
        rrdes = new javax.swing.JPanel();
        rrdesLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName(""); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(3, 2));

        head1.setBackground(new java.awt.Color(51, 204, 0));
        head1.setPreferredSize(new java.awt.Dimension(450, 200));

        headlbl1.setBackground(new java.awt.Color(51, 204, 0));
        headlbl1.setFont(new java.awt.Font("Tekton Pro Ext", 3, 36)); // NOI18N
        headlbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        headlbl1.setText("which algorithm do");

        javax.swing.GroupLayout head1Layout = new javax.swing.GroupLayout(head1);
        head1.setLayout(head1Layout);
        head1Layout.setHorizontalGroup(
            head1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headlbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );
        head1Layout.setVerticalGroup(
            head1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headlbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );

        getContentPane().add(head1);

        head2.setBackground(new java.awt.Color(51, 204, 0));
        head2.setPreferredSize(new java.awt.Dimension(200, 200));

        headlbl2.setFont(new java.awt.Font("Tekton Pro Ext", 3, 36)); // NOI18N
        headlbl2.setText(" you wanna use?");

        javax.swing.GroupLayout head2Layout = new javax.swing.GroupLayout(head2);
        head2.setLayout(head2Layout);
        head2Layout.setHorizontalGroup(
            head2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headlbl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );
        head2Layout.setVerticalGroup(
            head2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headlbl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );

        getContentPane().add(head2);

        sjfDes.setBackground(new java.awt.Color(255, 102, 0));

        sjfdesLbl.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        sjfdesLbl.setForeground(new java.awt.Color(255, 255, 255));
        sjfdesLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sjfdesLbl.setText(" ");

        javax.swing.GroupLayout sjfDesLayout = new javax.swing.GroupLayout(sjfDes);
        sjfDes.setLayout(sjfDesLayout);
        sjfDesLayout.setHorizontalGroup(
            sjfDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sjfdesLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );
        sjfDesLayout.setVerticalGroup(
            sjfDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sjfdesLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );

        getContentPane().add(sjfDes);

        sjf.setBackground(new java.awt.Color(255, 255, 0));

        sjfLbl.setBackground(new java.awt.Color(255, 255, 204));
        sjfLbl.setFont(new java.awt.Font("Tekton Pro Ext", 0, 36)); // NOI18N
        sjfLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sjfLbl.setText("SJF");
        sjfLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sjfLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sjfLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sjfLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sjfLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sjfLblMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sjfLblMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout sjfLayout = new javax.swing.GroupLayout(sjf);
        sjf.setLayout(sjfLayout);
        sjfLayout.setHorizontalGroup(
            sjfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sjfLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );
        sjfLayout.setVerticalGroup(
            sjfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sjfLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );

        getContentPane().add(sjf);

        rr.setBackground(new java.awt.Color(255, 255, 0));

        rrLbl.setFont(new java.awt.Font("Tekton Pro Ext", 0, 36)); // NOI18N
        rrLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rrLbl.setText("Round Robin");
        rrLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rrLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rrLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rrLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rrLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout rrLayout = new javax.swing.GroupLayout(rr);
        rr.setLayout(rrLayout);
        rrLayout.setHorizontalGroup(
            rrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rrLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );
        rrLayout.setVerticalGroup(
            rrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rrLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );

        getContentPane().add(rr);

        rrdes.setBackground(new java.awt.Color(255, 102, 0));

        rrdesLbl.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        rrdesLbl.setForeground(new java.awt.Color(255, 255, 255));
        rrdesLbl.setText("\n");

        javax.swing.GroupLayout rrdesLayout = new javax.swing.GroupLayout(rrdes);
        rrdes.setLayout(rrdesLayout);
        rrdesLayout.setHorizontalGroup(
            rrdesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rrdesLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );
        rrdesLayout.setVerticalGroup(
            rrdesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rrdesLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );

        getContentPane().add(rrdes);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sjfLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sjfLblMouseEntered
        // TODO add your handling code here:
        sjfdesLbl.setText("<html>" +
"Shortest Job First a non-preemptive discipline in which waiting job with the smallest estimated run-time-to-completion is run next.");   //show "SJF" description when hovering sjf
    }//GEN-LAST:event_sjfLblMouseEntered

    private void sjfLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sjfLblMouseExited
        // TODO add your handling code here:
        sjfdesLbl.setText("");      //hide text when mouse leaves sjf
    }//GEN-LAST:event_sjfLblMouseExited

    private void rrLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rrLblMouseEntered
        // TODO add your handling code here:
        rrdesLbl.setText("<html>" +
"An algorithm uses time slices (also known as time quanta) are assigned to each process in equal portions and in circular order, handling all processes without priority."); //show "RR" description when hovering round robin
    }//GEN-LAST:event_rrLblMouseEntered

    private void rrLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rrLblMouseExited
        // TODO add your handling code here:
        rrdesLbl.setText("");       //hide text when mouse leaves round robin
    }//GEN-LAST:event_rrLblMouseExited

    private void sjfLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sjfLblMouseClicked
           this.setVisible(false);
           new SJF().setVisible(true);
    }//GEN-LAST:event_sjfLblMouseClicked

    private void sjfLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sjfLblMousePressed
        // TODO add your handling code here:
        sjfLbl.setOpaque(true);
    }//GEN-LAST:event_sjfLblMousePressed

    private void sjfLblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sjfLblMouseReleased
        // TODO add your handling code here:
        sjfLbl.setOpaque(false);
    }//GEN-LAST:event_sjfLblMouseReleased

    private void rrLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rrLblMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new RR().setVisible(true);
    }//GEN-LAST:event_rrLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new intro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel head1;
    private javax.swing.JPanel head2;
    private javax.swing.JLabel headlbl1;
    private javax.swing.JLabel headlbl2;
    private javax.swing.JPanel rr;
    private javax.swing.JLabel rrLbl;
    private javax.swing.JPanel rrdes;
    private javax.swing.JLabel rrdesLbl;
    private javax.swing.JPanel sjf;
    private javax.swing.JPanel sjfDes;
    private javax.swing.JLabel sjfLbl;
    private javax.swing.JLabel sjfdesLbl;
    // End of variables declaration//GEN-END:variables
}
